markdown: kramdown
permalink: /:year/:month/:title/
author: Zhou Leihao	
pygments: true
paginate: 16
url: http://zhouleihao.com
baseurl: /
encoding: utf-8
highlighter: rouge
name: What a DREAMY Journey
open_in_new: true
highlightStyle: xcode
