# Site settings
title: herove Blog
seotitle: 周雷皓的博客
header-img: img/home-bg.jpg
email: herove@gmail.com
copyright_name: herove blog
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://zhouleihao.com"
twitter_username: leihao
github_username:  herove
facebook_username:  zhouleihao
email_username:  herove@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
